### PR TITLE
Renamed parameters, added to signal

### PR DESCRIPTION
**Pull request by jakob-o**
Renames action parameters and adds them to signals

### CODE REVIEW

**Comment by czpython** [comment]
Just finished replying to your other comment :).

I would rather it be user_action or object_action, as cms_action is too specific.
I think object_action is the most accurate.

**Comment by jakob-o** [comment]
Updated PR

**Comment by czpython** [comment]
:+1: thanks!

**Comment by jakob-o** [comment]
I have to thank you! Otherwise this would have ended up in a fork-mess...

**Pull request merged**
